global:
  scrape_interval: 15s

# Mount rules file
rule_files:
  - "./src/alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'RTT'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 199.168.0.201
          - 199.168.0.202
          - 199.168.0.5
          - 199.168.0.117
          - 199.168.0.118
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'ISP'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
# Connect to Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]